In [2]:
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

img = cv2.imread('assets/neighbour.jpg', 0)
binary = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)[1]

rows, cols = binary.shape

same_4_array = np.zeros((rows, cols), dtype=np.uint8)
same_8_array = np.zeros((rows, cols), dtype=np.uint8)

neighbours_4 = [(0,1), (1,0), (0,-1), (-1,0)]
neighbours_8 = neighbours_4 + [(1,1), (1,-1), (-1,1), (-1,-1)]

for x in range(rows):
    for y in range(cols):
        curr = binary[x, y]
        same_4 = 0
        same_8 = 0

        for dx, dy in neighbours_4:
            nx, ny = x + dx, y + dy
            if 0 <= nx < rows and 0 <= ny < cols:
                if curr == binary[nx, ny]:
                    same_4 += 1

        for dx, dy in neighbours_8:
            nx, ny = x + dx, y + dy
            if 0 <= nx < rows and 0 <= ny < cols:
                if curr == binary[nx, ny]:
                    same_8 += 1

        same_4_array[x, y] = same_4
        same_8_array[x, y] = same_8


print("Original Binary Array:")
print(binary)

print("\nSame 4-Connected Neighbour Counts:")
print(same_4_array)

print("\nSame 8-Connected Neighbour Counts:")
print(same_8_array)


Original Binary Array:
[[255   0   0   0   0   0   0   0   0 255]
 [  0 255   0   0   0   0   0   0 255   0]
 [  0   0 255   0   0   0   0 255   0   0]
 [  0   0   0 255   0   0 255   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0 255   0   0 255   0   0   0]
 [  0   0 255   0   0   0   0 255   0   0]
 [  0 255   0   0   0   0   0   0 255   0]
 [255   0   0   0   0   0   0   0   0 255]]

Same 4-Connected Neighbour Counts:
[[0 1 3 3 3 3 3 3 1 0]
 [1 0 2 4 4 4 4 2 0 1]
 [3 2 0 2 4 4 2 0 2 3]
 [3 4 2 0 2 2 0 2 4 3]
 [3 4 4 2 2 2 2 4 4 3]
 [3 4 4 2 2 2 2 4 4 3]
 [3 4 2 0 2 2 0 2 4 3]
 [3 2 0 2 4 4 2 0 2 3]
 [1 0 2 4 4 4 4 2 0 1]
 [0 1 3 3 3 3 3 3 1 0]]

Same 8-Connected Neighbour Counts:
[[1 3 4 5 5 5 5 4 3 1]
 [3 2 6 7 8 8 7 6 2 3]
 [4 6 2 6 7 7 6 2 6 4]
 [5 7 6 2 5 5 2 6 7 5]
 [5 8 7 5 4 4 5 7 8 5]
 [5 8 7 5 4 4 5 7 8 5]
 [5 7 6 2 5 5 2 6 7 5]
 [4 6 2 6 7 7 6 2 6 4]
 [3 2 6 7 8 8 7 6 2 3]
 [1 3 4 5 5 5 5 4 3 1]]
