In [6]:
import cv2
import numpy as np

img = cv2.imread('assets/neighbour.jpg', cv2.IMREAD_GRAYSCALE)

binary = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)[1]

height, width = binary.shape
print(f"Height={height},Width={width}")

same_4_array = np.zeros((height, width), dtype=int)
same_8_array = np.zeros((height, width), dtype=int)

for y in range(height):
    for x in range(width):
        current = binary[y, x]
        same_4 = 0
        same_8 = 0

        for dx, dy in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nx, ny = x + dx, y + dy
            if 0 <= nx < width and 0 <= ny < height:
                if binary[ny, nx] == current:
                    same_4 += 1

        for dx in [-1, 0, 1]:
            for dy in [-1, 0, 1]:
                if dx == 0 and dy == 0:
                    continue
                nx, ny = x + dx, y + dy
                if 0 <= nx < width and 0 <= ny < height:
                    if binary[ny, nx] == current:
                        same_8 += 1

        same_4_array[y, x] = same_4
        same_8_array[y, x] = same_8


print("Original Binary Array:")
print(binary)

print("\nSame 4-Connected Neighbor Counts:")
print(same_4_array)

print("\nSame 8-Connected Neighbor Counts:")
print(same_8_array)

Height=10,Width=10
Original Binary Array:
[[255   0   0   0   0   0   0   0   0 255]
 [  0 255   0   0   0   0   0   0 255   0]
 [  0   0 255   0   0   0   0 255   0   0]
 [  0   0   0 255   0   0 255   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0]
 [  0   0   0 255   0   0 255   0   0   0]
 [  0   0 255   0   0   0   0 255   0   0]
 [  0 255   0   0   0   0   0   0 255   0]
 [255   0   0   0   0   0   0   0   0 255]]

Same 4-Connected Neighbor Counts:
[[0 1 3 3 3 3 3 3 1 0]
 [1 0 2 4 4 4 4 2 0 1]
 [3 2 0 2 4 4 2 0 2 3]
 [3 4 2 0 2 2 0 2 4 3]
 [3 4 4 2 2 2 2 4 4 3]
 [3 4 4 2 2 2 2 4 4 3]
 [3 4 2 0 2 2 0 2 4 3]
 [3 2 0 2 4 4 2 0 2 3]
 [1 0 2 4 4 4 4 2 0 1]
 [0 1 3 3 3 3 3 3 1 0]]

Same 8-Connected Neighbor Counts:
[[1 3 4 5 5 5 5 4 3 1]
 [3 2 6 7 8 8 7 6 2 3]
 [4 6 2 6 7 7 6 2 6 4]
 [5 7 6 2 5 5 2 6 7 5]
 [5 8 7 5 4 4 5 7 8 5]
 [5 8 7 5 4 4 5 7 8 5]
 [5 7 6 2 5 5 2 6 7 5]
 [4 6 2 6 7 7 6 2 6 4]
 [3 2 6 7 8 8 7 6 2 3]
 [1 3 4 5 5 5 5 4 3